mode: deployment
clusterName: ${cluster_name}
region: ap-northeast-2

serviceAccount:
  create: true
  name: adot-collector-sa
  annotations:
    eks.amazonaws.com/role-arn: ${adot_amp_role_arn}

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'kubelet'
          kubernetes_sd_configs:
            - role: node

exporters:
  awsprometheusremotewrite:
    endpoint: https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/${amp_workspace_id}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [awsprometheusremotewrite]
