pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-northeast-2'
        ECR_REPO = '297195401389.dkr.ecr.ap-northeast-2.amazonaws.com/zapp/react-app'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Docker Build & Push') {
            steps {
                dir('front-service/react-app') {   // ⭐️ 이 부분 추가!!
                    script {
                        sh """
                        echo "🛠 Docker Build 시작"
                        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

                        docker build -t $ECR_REPO:$IMAGE_TAG .

                        echo "📤 ECR Push"
                        docker push $ECR_REPO:$IMAGE_TAG
                        """
                    }
                }
            }
        }
    }
}
