pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-northeast-2'
        AWS_ACCOUNT_ID = '297195401389'
        ECR_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/user-service"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build & Push to ECR') {
            steps {
                script {
                    sh """
                    echo "🛠 Docker Build & Push"
                    aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}
                    docker build -t ${ECR_REPO}:${IMAGE_TAG} .
                    docker push ${ECR_REPO}:${IMAGE_TAG}
                    """
                }
            }
        }
    }
}
