apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
