# kafka-client.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
        - name: kafka-client
          image: docker.io/bitnami/kafka:latest
          command: ["sleep", "infinity"]
