apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 297195401389.dkr.ecr.ap-northeast-2.amazonaws.com/zapp/user-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "user-service,user-service.default.svc.cluster.local,*"
            - name: DJANGO_SETTINGS_MODULE
              value: "user_service.settings"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-postgres-secrets
                  key: database-url
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
