apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  namespace: service
spec:
  selector:
    app: user-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
